In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
# dataset
x = dataset.iloc[:,:-1].values #feture
y = dataset.iloc[:,-1].values #depending variable
# .values converts the data into array form 
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [3]:
#to take care of missing data
#this will put the mean of the data in the cloumn and put that value in the missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
#imputer is obj of class simpleimputer
imputer.fit(x[:,1:])
# print(x)
x[:,1:]=imputer.transform(x[:,1:])
# print('\n')
# print(x)

In [7]:
# we need all our data in text formate for modal to understand
# so we have to turn country name and yes/no into some number
# but we cant turn country name into 0,1,2 that will give them unnessesury precidance
# so we'll use enconding it will turn countery into some code
# this type of encoding is called one hot encoding

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
# here we are conveting x into numpy array bcoz our modal takes input in only numpy array fromate
x = np.array(ct.fit_transform(x))
# print(x)

# for y 
# now y is just cosist of yes and no
# so we'll convert them into 1 and 0 no=0,yes=1

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
# print(y)

In [8]:
# now we'll split the data into training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)
# print(x_train)
# print(x_test)
# print(y_train)
# print(y_test)

[[0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


In [12]:
# feature scelling
# only should be done after you splitt the data 
# so training data doesnt leak into testing data and also if we apply it brfore it'll take the mean of whole data
# normlisetion only works for only normal distribution 
# standerdisation works all the time  
# dont apply feature scalling on dammy vars ie contry in this data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
# [:,3:] bcoz column 0,1 and 2 are taken by our contry name conversion
x_test[:,3:] = sc.transform(x_test[:,3:])
# for test only use transform because we dont want to change the scaler
# print(x_test)

[[0.0 1.0 0.0 1.0 -6.162975822039156e-33 30.0 54000.0]
 [1.0 0.0 1.0 1.249000902703301e-16 -6.162975822039156e-33 37.0 67000.0]]
